### ISSUE TITLE
save files too easy to change

### ISSUE THREAD

**Issue by sjvdvd** [jeremyckahn/farmhand#462] opened 2023-10-13 15:25 UTC

**Comment by jeremyckahn** [comment] 2023-10-13 15:27
IMO this is a feature and not a bug. Why do you believe that the save files should be harder to change, @sjvdvd?

**Comment by sjvdvd** [comment] 2023-10-16 11:42
It's an online game @jeremyckahn

**Comment by jeremyckahn** [comment] 2023-10-16 14:10
> It's an online game @jeremyckahn

Yes, but online functionality was designed to be cheat-tolerant. This is achieved by limiting the effect that one player can have on another through market impact. One could modify a cow via a save file and trade it away, and an argument could be made that doing so would affect the "purity" of another player's online experience. However, this could also be achieved by modifying the game state via something like React dev tools. This can't be reasonably mitigated without a complete re-architecture of the online system, and that's not something I foresee happening.

Given that it would be relatively easy for people to cheat even with mitigations via save file obfuscation in place, I'd prefer to keep the save file as a plain JSON file. This will keep the file accessible to curious players who chose to play the game as designed and want to learn how it works.

I'm closing this issue as it's not something I'd like to include in Farmhand, but I am open to further discussion in this thread!

**Closed by jeremyckahn** 2023-10-16 14:10 UTC
