### ISSUE TITLE
Doesn't show revenue... shows zero revenue

### ISSUE THREAD

**Issue by Kabinash781** [jeremyckahn/farmhand#56] opened 2021-05-02 17:19 UTC

**Comment by Kabinash781** [comment] 2021-05-02 17:20
cant post export as github doesnt support json file uploads

**Comment by jeremyckahn** [comment] 2021-05-02 19:16
@Kabinash781 Could you please add a bit more description to this ticket? Steps to reproduce and a screenshot would help me fix this for you!

**Comment by jeremyckahn** [comment] 2021-05-03 12:52
It appears that sold dishes don't count towards daily revenue. I'll take a look at this!

**Comment by jeremyckahn** [comment] 2021-05-03 13:05
![IMG_20210502_140533](https://user-images.githubusercontent.com/366330/116878864-8dcfd300-abe5-11eb-9633-8830eabf3d02.jpeg)

This screenshot was [provided by @Kabinash781 on Discord](https://discord.com/channels/714539345050075176/822068921653788683/838333157471944724). However, I'm not able to reproduce this issue. Perhaps there were other transactions that caused the day's loss?

I'll need clear steps to reproduce this before I can fix it. I'm not seeing a bug here, so I'll close this issue for now.

**Closed by jeremyckahn** 2021-05-03 13:05 UTC
